package com.tickefy.order.common.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    RESOURCE_NOT_FOUND,
    CONFLICT,
    INTERNAL_SERVER_ERROR,
    SERVICE_UNAVAILABLE,
    INVALID_TOKEN,
    TICKET_SOLD_OUT,
    PER_USER_LIMIT_EXCEEDED,
    SALE_WINDOW_CLOSED,
    RESERVATION_EXPIRED,
    CONCERT_NOT_FOUND
}
