package com.tickefy.payment.common.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    RESOURCE_NOT_FOUND,
    CONFLICT,
    INTERNAL_SERVER_ERROR,
    SERVICE_UNAVAILABLE,
    PAYMENT_NOT_FOUND,
    PAYMENT_GATEWAY_UNAVAILABLE,
    INVALID_CALLBACK_SIGNATURE
}
