package com.tickefy.auth.common.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    RESOURCE_NOT_FOUND,
    CONFLICT,
    INTERNAL_SERVER_ERROR,
    SERVICE_UNAVAILABLE,
    EMAIL_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    TOKEN_REVOKED,
    INVALID_TOKEN,
    USER_NOT_FOUND,
    INVALID_ROLE,
    LAST_ADMIN
}
