package com.tickefy.eticket.common.exception;

public enum ErrorCode {
    // Generic
    VALIDATION_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    RESOURCE_NOT_FOUND,
    CONFLICT,
    INTERNAL_SERVER_ERROR,
    SERVICE_UNAVAILABLE,

    // Auth
    INVALID_TOKEN,

    // Ticket domain — e-ticket-service
    TICKET_NOT_FOUND,
    TICKET_ACCESS_DENIED,
    TICKET_INVALID_STATE,
    TICKET_ALREADY_CHECKED_IN,
    TICKET_CANCELLED,
    TICKET_REFUNDED,
    TICKET_ISSUE_UNAVAILABLE,
    ORDER_ITEM_ALREADY_HAS_TICKET,
    INVALID_QR_TOKEN,
    DUPLICATE_REJECTED,

    // Checkin domain — used by checkin-service calling e-ticket-service
    WRONG_EVENT,
    CANCELLED_TICKET,
    REFUNDED_TICKET,
    CHECKIN_REQUEST_INVALID,
    CHECKIN_STAFF_REQUIRED,
    CHECKIN_CONCERT_ACCESS_DENIED,
    ETICKET_SERVICE_UNAVAILABLE,
    CHECKIN_LOG_FAILED,
    SNAPSHOT_NOT_FOUND,
    SNAPSHOT_REQUIRED,
    SNAPSHOT_EXPIRED,
    SNAPSHOT_GENERATION_FAILED,
    SNAPSHOT_ACCESS_DENIED,
    SYNC_BATCH_INVALID,
    SYNC_BATCH_DUPLICATED,
    SYNC_CONFLICT_DETECTED,
    SYNC_CONCERT_MISMATCH,
    SYNC_DEVICE_CLOCK_INVALID,
    SYNC_SERVICE_UNAVAILABLE,
    RATE_LIMIT_EXCEEDED,
    PER_USER_LIMIT_EXCEEDED
}
