package com.tickefy.inventory.common.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    RESOURCE_NOT_FOUND,
    CONFLICT,
    INTERNAL_SERVER_ERROR,
    SERVICE_UNAVAILABLE,
    TICKET_SOLD_OUT,
    PER_USER_LIMIT_EXCEEDED,
    SALE_WINDOW_CLOSED,
    INVALID_TOKEN
}
