from enum import StrEnum


class ErrorCode(StrEnum):
    # Common
    VALIDATION_ERROR = "VALIDATION_ERROR"
    UNAUTHORIZED = "UNAUTHORIZED"
    INVALID_TOKEN = "INVALID_TOKEN"
    FORBIDDEN = "FORBIDDEN"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    CONFLICT = "CONFLICT"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"

    # Event service shared/domain errors
    CONCERT_NOT_FOUND = "CONCERT_NOT_FOUND"
    CONCERT_ACCESS_DENIED = "CONCERT_ACCESS_DENIED"

    # AI Bio specific
    SOURCE_REQUIRED = "SOURCE_REQUIRED"
    UNSUPPORTED_SOURCE_TYPE = "UNSUPPORTED_SOURCE_TYPE"
    INVALID_SOURCE_TYPE = "INVALID_SOURCE_TYPE"
    SOURCE_TOO_LARGE = "SOURCE_TOO_LARGE"
    EVENT_SERVICE_UNAVAILABLE = "EVENT_SERVICE_UNAVAILABLE"
    AI_BIO_JOB_ALREADY_ACTIVE = "AI_BIO_JOB_ALREADY_ACTIVE"
    AI_BIO_JOB_NOT_RETRYABLE = "AI_BIO_JOB_NOT_RETRYABLE"
    NO_USABLE_SOURCE_CONTENT = "NO_USABLE_SOURCE_CONTENT"
    DOCUMENT_PASSWORD_PROTECTED = "DOCUMENT_PASSWORD_PROTECTED"
    OBJECT_STORAGE_UNAVAILABLE = "OBJECT_STORAGE_UNAVAILABLE"
    AI_PROVIDER_UNAVAILABLE = "AI_PROVIDER_UNAVAILABLE"
    AI_PROVIDER_INVALID_RESPONSE = "AI_PROVIDER_INVALID_RESPONSE"
    AI_OUTPUT_INVALID = "AI_OUTPUT_INVALID"
    AI_BIO_JOB_NOT_FOUND = "AI_BIO_JOB_NOT_FOUND"
    IDEMPOTENCY_KEY_REQUIRED = "IDEMPOTENCY_KEY_REQUIRED"
    IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_REQUEST = "IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_REQUEST"
