package com.tickefy.csvingestion.common.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    UNAUTHORIZED,
    INVALID_TOKEN,
    FORBIDDEN,
    RESOURCE_NOT_FOUND,
    CONCERT_NOT_FOUND,
    CONFLICT,
    INTERNAL_SERVER_ERROR,
    SERVICE_UNAVAILABLE,
    OBJECT_STORAGE_UNAVAILABLE,
    FILE_TOO_LARGE,
    INVALID_FILE_FORMAT,
    INVALID_ENCODING,
    IMPORT_JOB_NOT_FOUND,
    IMPORT_JOB_NOT_RETRYABLE
}
